[package]
name = "gateway-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64 = "0.13"
dashmap = "4.0"
env_logger = { version = "0.9", default-features = false, features = [
    "termcolor",
    "atty",
    "humantime"
] }
futures-util = { version = "0.3", default-features = false }
halfbrown = "0.1"
hyper = { version = "0.14", default-features = false, features = ["server", "http1", "http2"] }
libc = { version = "0.2", default-features = false }
log = "0.4"
metrics = { version = "0.17", default-features = false, features = ["std"] }
metrics-exporter-prometheus = { version = "0.6", default-features = false }
mimalloc = { version = "0.1", default-features = false, features = ["override"] }
serde = { version = "1", features = ["derive"] }
sha-1 = "0.9"
simd-json = { version = "0.4", default-features = false, features = [
    "serde_impl"
] }
# Better match twilight-gateway here
tokio-tungstenite = { version = "0.16", default-features = false }
tokio = { version = "1", default-features = false, features = [
    "macros",
    "rt-multi-thread"
] }
tracing = { version = "0.1", default-features = false, features = ["log"] }
twilight-cache-inmemory = { git = "https://github.com/twilight-rs/twilight.git", branch = "next" }
twilight-gateway = { git = "https://github.com/twilight-rs/twilight.git", branch = "next", default-features = false, features = [
    "zlib-simd",
    "rustls-webpki-roots",
    "tracing"
] }
twilight-gateway-queue = { git = "https://github.com/twilight-rs/twilight.git", branch = "next", default-features = false, features = ["rustls-webpki-roots"] }
twilight-http = { git = "https://github.com/twilight-rs/twilight.git", branch = "next", default-features = false, features = [
    "rustls-webpki-roots",
    "trust-dns"
] }
twilight-model = { git = "https://github.com/twilight-rs/twilight.git", branch = "next" }
libz-sys = { version = "1.1", default-features = false, features = ["zlib-ng"] }

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
