[package]
name = "gateway-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64 = "0.13"
dashmap = "5.0"
flate2 = { version = "1.0", default-features = false, features = ["zlib-ng-compat"] }
futures-util = { version = "0.3", default-features = false }
halfbrown = "0.1"
hyper = { version = "0.14", default-features = false, features = ["server", "http1", "http2"] }
libc = { version = "0.2", default-features = false }
metrics = { version = "0.17", default-features = false, features = ["std"] }
metrics-exporter-prometheus = { version = "0.7", default-features = false }
mimalloc = { version = "0.1", default-features = false, features = ["override"] }
parking_lot = "0.11"
ring = { version = "0.16", default-features = false }
serde = { version = "1", features = ["derive"] }
simd-json = { version = "0.4", default-features = false, features = [
    "serde_impl"
] }
# Better match twilight-gateway here
tokio-tungstenite = { version = "0.16", default-features = false }
tokio = { version = "1", default-features = false, features = [
    "macros",
    "parking_lot",
    "rt-multi-thread"
] }
tracing = { version = "0.1", default-features = false, features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "ansi",
    "env-filter",
    "fmt",
    "parking_lot",
    "std"
] }
twilight-cache-inmemory = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom" }
twilight-gateway = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom", default-features = false, features = [
    "zlib-simd",
    "simd-json",
    "rustls-webpki-roots",
    "tracing"
] }
twilight-gateway-queue = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom", default-features = false, features = ["rustls-webpki-roots"] }
twilight-http = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom", default-features = false, features = [
    "rustls-webpki-roots",
    "simd-json"
] }
twilight-model = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom" }

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
