name: Publish update
on: [push]

jobs:
  build:
    name: Build & publish
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_TARGET_ACCOUNT: ${{ secrets.DOCKERHUB_TARGET }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: env.DOCKER_USERNAME
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert GITHUB_REPOSITORY into lowercase
        run: |
            echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build for x86_64
        run: |
            docker build -t gateway-proxy:latest .

      - name: Create manifest and push it
        if: env.DOCKER_USERNAME
        run: |
            docker tag gateway-proxy:latest ${{ secrets.DOCKERHUB_TARGET }}/gateway-proxy:latest
            docker push ${{ secrets.DOCKERHUB_TARGET }}/gateway-proxy:latest

            docker tag gateway-proxy:latest ghcr.io/${REPO}:latest
            docker push ghcr.io/${REPO}:latest
